### ISSUE TITLE
Not working on macOS 10.14.4

### ISSUE THREAD

**Issue by vorktanamobay** [kettle/Contactor#2]
I installed with brew and I get this error wher running `Contactor list`

```
dyld: Symbol not found: _OBJC_CLASS_$_SwiftObject
  Referenced from: /usr/local/bin/Contactor
  Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib
 in /usr/local/bin/Contactor
Abort trap: 6
```

**Comment by sdettling** [comment]
Fixed in [Release 1.2.7](https://github.com/kettle/Contactor/releases/tag/1.2.7)
